'use strict';
const $=id=>document.getElementById(id);
const icons={play:'M8 5l11 7-11 7Z',pause:'M8 5v14M16 5v14',save:'M5 3h12l4 4v14H3V3Zm2 0v6h10V3M7 21v-8h10v8',download:'M12 3v12m-5-5 5 5 5-5M4 16v5h16v-5',upload:'M12 16V3m-5 5 5-5 5 5M4 16v5h16v-5',expand:'M8 3H3v5m13-5h5v5M3 16v5h5m8 0h5v-5',layers:'m12 3 10 6-10 6L2 9Zm-9 11 9 5 9-5M3 19l9 5 9-5',info:'M12 10v7m0-11v1M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z',berg:'m3 19 6-13 4 6 3-8 6 15Z'};
const icon=k=>`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="${icons[k]||icons.info}"/></svg>`;
document.querySelectorAll('[data-icon]').forEach(e=>e.innerHTML=icon(e.dataset.icon));
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const clone=x=>JSON.parse(JSON.stringify(x));
const fmt=(v,n=1)=>Number(v).toLocaleString(undefined,{maximumFractionDigits:n,minimumFractionDigits:n});
const names={distance:'Shortest passage',balanced:'Lower ice exposure',fuel:'Lower fuel proxy'};
const descriptions={distance:'Minimize distance within the constraints',balanced:'Give ice exposure greater weight',fuel:'Minimize the illustrative fuel index'};
let scenario=null,result=null,resultInput=null,selected='balanced',frame=0,playTimer=null,toastTimer=null,placing=null,activeTab='planner',loading=false,requestVersion=0;
let view={zoom:1,x:0,y:0},cursor=[20,13],pointer=null,dragged=false,plotBox=null,editBergs=[];
let mapCanvas=$('map'),ctx=mapCanvas.getContext('2d'),raster=document.createElement('canvas');raster.width=44;raster.height=30;
function toast(message){$('toast').textContent=message;$('toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').hidden=true,4200)}
function fail(message){$('error').textContent=message;$('error').hidden=!message;if(message)toast(message)}
async function api(url,body){let r;try{r=await fetch(url,body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{});}catch{throw Error('PolarRoute is offline. Run Start-PolarRoute.ps1, then reload this page.')}let j;try{j=await r.json()}catch{throw Error('Cannot read the response. Restart PolarRoute and try again.')}if(!r.ok)throw Error(j.error||'Request failed');return j}
function download(name,value,type='application/json'){const content=typeof value==='string'?value:JSON.stringify(value,null,2);const url=URL.createObjectURL(new Blob([content],{type}));const a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),2000)}
function options(){return {horizon:+$('horizon').value,speed:+$('speed').value,ice_limit:+$('iceLimit').value/100,buffer_km:+$('buffer').value,wind_scale:+$('wind').value,max_wave:+$('maxWave').value,vessel_draft:+$('draft').value,forecast_method:$('forecastMethod').value}}
function applyOptions(o){for(const [id,key,mult] of [['horizon','horizon',1],['speed','speed',1],['iceLimit','ice_limit',100],['buffer','buffer_km',1],['wind','wind_scale',1],['maxWave','max_wave',1],['draft','vessel_draft',1]])if(o[key]!==undefined)$(id).value=o[key]*mult;if(o.forecast_method)$('forecastMethod').value=o.forecast_method;labels()}
function labels(){for(const [id,suffix,d] of [['speed',' kn',0],['iceLimit','%',0],['buffer',' km',0],['wind','×',1],['maxWave',' m',1],['draft',' m',0]])$(id+'Val').textContent=(+$(id).value).toFixed(d)+suffix}
function dirty(){stop();$('dirty').hidden=false;$('runStatus').textContent='Changed inputs are waiting to be calculated.'}
function stop(){clearInterval(playTimer);playTimer=null;$('play').innerHTML=icon('play');$('play').setAttribute('aria-label','Play forecast')}
function coord(s,p){const [w,so,e,n]=s.bounds;return [w+p[0]/43*(e-w),n-p[1]/29*(n-so)]}
function prettyCoord(s,p){const [lon,lat]=coord(s,p);return `${Math.abs(lat).toFixed(2)}°S, ${Math.abs(lon).toFixed(2)}°${lon<0?'W':'E'}`}
function selectedRoute(){return result?.routes.find(r=>r.mode===selected)||result?.routes[0]}
function updateInputs(){if(!scenario)return;$('startX').value=scenario.start[0];$('startY').value=scenario.start[1];$('goalX').value=scenario.goal[0];$('goalY').value=scenario.goal[1];$('startCoord').textContent=prettyCoord(scenario,scenario.start);$('goalCoord').textContent=prettyCoord(scenario,scenario.goal);$('sourceName').value=scenario.name;$('sourceText').value=scenario.source;$('observedAt').value=scenario.observed_at}
async function calculate(){if(!scenario||loading)return;stop();fail('');loading=true;const version=++requestVersion;const input=clone(scenario),opts=options();$('run').disabled=true;$('dirtyRun').disabled=true;$('run').innerHTML=icon('layers')+'Calculating…';$('runStatus').textContent='Computing ice, iceberg envelopes and route alternatives…';try{const next=await api('/api/run',{scenario:input,options:opts});if(version!==requestVersion)return;result=next;resultInput=input;frame=0;$('time').value=0;$('time').max=result.forecasts.length-1;if(!result.routes.some(r=>r.mode===selected))selected=result.routes[0]?.mode||'balanced';$('dirty').hidden=JSON.stringify(scenario)===JSON.stringify(input)&&JSON.stringify(options())===JSON.stringify(opts);$('runStatus').textContent=`Completed in ${fmt(result.stats.elapsed_ms/1000,2)} s · ${result.routes.length} accepted options`;refresh();toast(result.routes.length?'Voyage calculation complete':'No route satisfies the current plan')}catch(e){fail(e.message);$('runStatus').textContent='Calculation failed. Previous results are unchanged.'}finally{loading=false;$('run').disabled=false;$('dirtyRun').disabled=false;$('run').innerHTML=icon('play')+'Calculate passage'}}
function refresh(){if(!result)return;const s=result.scenario;updateInputs();$('mapTitle').textContent=s.name;$('mapExtent').textContent=`${s.bounds[0]}–${s.bounds[2]}° longitude`;$('sourceNotice').textContent=s.data_kind==='synthetic'?'Synthetic demonstration · No live Antarctic feeds connected':s.data_kind==='observational'?'NOAA analysis · '+s.observed_at.slice(0,10)+' · persistence projection':'Imported scenario · Verify source, date and data quality';$('mapSub').textContent=s.data_kind==='synthetic'?'Fictional coastline · not a navigation chart':s.data_kind==='observational'?'Natural Earth coastline · geographic coordinates':'Imported land mask · not a navigation chart';$('timeTicks').innerHTML=[0,1,2,3].map(n=>`<span>${n?result.options.horizon*n/3+' h':'Now'}</span>`).join('');$('runId').textContent='Run '+result.stats.run_id;routes();bergs();decisionNotes();provenance();drawMap();drawProfile();drawIce();updateMission();updateSources();}
function routes(){const r=selectedRoute();$('routeCount').textContent=result.routes.length;$('routeCards').innerHTML=result.routes.length?result.routes.map(x=>`<button class="route-card ${x.mode===r.mode?'selected':''}" data-route="${x.mode}" aria-pressed="${x.mode===r.mode}"><div><b>${names[x.mode]}</b><i class="selection-dot"></i></div><div class="route-num">${fmt(x.distance_km,0)} <small>km</small><small>${fmt(x.eta_hours,1)} h</small></div><div class="route-detail"><span>${fmt(x.mean_ice*100,1)}% mean ice</span><span>Fuel ${fmt(x.fuel_index,0)}</span></div><div class="route-note">${descriptions[x.mode]}</div></button>`).join(''):'<div class="empty"><b>No accepted passage</b><br>Inspect the exclusion layer and decision notes. A different endpoint, horizon or limit may change the result.</div>';
if(result.rejected_routes.length)$('routeCards').insertAdjacentHTML('beforeend',`<p class="hint">${result.rejected_routes.length} candidate(s) exceed the forecast horizon and are excluded from selection.</p>`);
if(!r){for(const k of ['distance','eta','fuel','exposure'])$(k).textContent='—';$('distanceDiff').textContent='No accepted route';$('arrival').textContent='Review decision notes';drawProfile();return}
$('distance').textContent=fmt(r.distance_km,0)+' km';$('eta').textContent=fmt(r.eta_hours,1)+' h';$('fuel').textContent=fmt(r.fuel_index,0);$('exposure').textContent=fmt(r.mean_ice*100,1)+'%';const d=result.routes.find(x=>x.mode==='distance');$('distanceDiff').textContent=d&&d.distance_km>0?`${fmt((r.distance_km/d.distance_km-1)*100,1)}% vs shortest candidate`:'At the requested destination';$('arrival').textContent='ETA '+new Date(Date.parse(result.scenario.observed_at)+r.eta_hours*3600000).toISOString().slice(5,16).replace('T',' ')+' UTC';drawProfile()}
$('routeCards').onclick=e=>{const b=e.target.closest('[data-route]');if(b){selected=b.dataset.route;routes();drawMap();updateMission()}};
function bergs(){$('bergList').innerHTML=result.tracks.length?result.tracks.map(b=>`<div class="berg-row"><span class="berg-symbol">${icon('berg')}</span><div><strong>${esc(b.id)}</strong><small>Spread at horizon: ${fmt(b.radius_km.at(-1),1)} km</small></div><div class="berg-distance">${fmt(b.displacement_km,1)} km<small>forecast drift</small></div></div>`).join(''):'<p class="hint">No iceberg observations in this scenario. This does not establish that the region is iceberg-free.</p>'}
function decisionNotes(){$('alertCount').textContent=result.warnings.length;$('alerts').innerHTML=result.warnings.map(w=>`<div class="decision-note">${esc(w)}</div>`).join('');$('blockedShare').textContent=result.stats.blocked_percent+'% excluded';const labels={land:'Land',ice:'Sea ice',iceberg:'Icebergs',waves:'Waves',depth:'Depth',zones:'Manual zones',missing:'Missing data'};$('constraintBars').innerHTML=Object.entries(result.stats.reason_counts).map(([k,v])=>`<div class="constraint"><span>${labels[k]}</span><i><em style="width:${v/1320*100}%"></em></i><small>${v}</small></div>`).join('')}
function provenance(){const s=result.scenario;$('provenance').innerHTML=[['Source',s.source],['Observation time',s.observed_at],['Input type',s.data_kind||'User-supplied'],['Grid','44 columns × 30 rows; north row first'],['Sea-ice method',result.options.forecast_method],['Run reference',result.stats.run_id]].map(([a,b])=>`<dt>${esc(a)}</dt><dd>${esc(b)}</dd>`).join('')}
function canvasSize(canvas){const b=canvas.getBoundingClientRect();if(!b.width||!b.height)return null;const dpr=Math.min(window.devicePixelRatio||1,2);const w=Math.round(b.width*dpr),h=Math.round(b.height*dpr);if(canvas.width!==w||canvas.height!==h){canvas.width=w;canvas.height=h}const c=canvas.getContext('2d');c.setTransform(dpr,0,0,dpr,0,0);return {c,w:b.width,h:b.height}}
function gridValue(v,x,y){return Array.isArray(v)?v[Math.max(0,Math.min(29,Math.round(y)))][Math.max(0,Math.min(43,Math.round(x)))]:v}
function drawMap(){const size=canvasSize(mapCanvas);if(!size||!result)return;const {c,w,h}=size;c.clearRect(0,0,w,h);c.fillStyle='#10364e';c.fillRect(0,0,w,h);const box={x:35,y:72,w:w-60,h:h-108};plotBox=box;const X=x=>box.x+x/43*box.w,Y=y=>box.y+y/29*box.h;
c.save();c.beginPath();c.rect(0,0,w,h);c.clip();c.translate(w/2+view.x,h/2+view.y);c.scale(view.zoom,view.zoom);c.translate(-w/2,-h/2);
const rc=raster.getContext('2d'),img=rc.createImageData(44,30);for(let y=0;y<30;y++)for(let x=0;x<44;x++){const land=result.scenario.land[y][x],a=fieldColor(x,y,land),i=(y*44+x)*4;img.data.set([...a.map(Math.round),255],i)}rc.putImageData(img,0,0);c.imageSmoothingEnabled=true;c.drawImage(raster,box.x-box.w/86,box.y-box.h/58,box.w*44/43,box.h*30/29);
drawGeography(c,X,Y,box);drawContours(c,X,Y,box);const s=result.scenario;c.lineWidth=.6;c.strokeStyle='#c0e2ef20';c.fillStyle='#a2c5d5';c.font='9px Segoe UI';for(let n=0;n<=5;n++){const x=box.x+n*box.w/5;c.beginPath();c.moveTo(x,box.y);c.lineTo(x,box.y+box.h);c.stroke();const lon=s.bounds[0]+n*(s.bounds[2]-s.bounds[0])/5;c.fillText(fmt(lon,0)+'°',x-7,box.y+box.h+17)}for(let n=0;n<=4;n++){const y=box.y+n*box.h/4;c.beginPath();c.moveTo(box.x,y);c.lineTo(box.x+box.w,y);c.stroke();c.fillText(fmt(Math.abs(s.bounds[3]-n*(s.bounds[3]-s.bounds[1])/4),0)+'°S',4,y+3)}
if($('layerBlocked').checked){c.fillStyle='#dc674b38';for(let y=0;y<30;y++)for(let x=0;x<44;x++)if(result.blocked[y][x]&&!s.land[y][x])c.fillRect(X(x)-box.w/86,Y(y)-box.h/58,box.w/43+1,box.h/29+1)}
function arrows(u,v,color,dashed){c.strokeStyle=color;c.lineWidth=.8;for(let y=2;y<27;y+=5)for(let x=2;x<43;x+=6){if(s.land[y][x])continue;const a=gridValue(u,x,y),b=gridValue(v,x,y),norm=Math.hypot(a,b);if(norm<.0001)continue;const dx=a/norm*7,dy=-b/norm*7;c.setLineDash(dashed?[2,2]:[]);c.beginPath();c.moveTo(X(x)-dx,Y(y)-dy);c.lineTo(X(x)+dx,Y(y)+dy);c.stroke();c.setLineDash([]);const angle=Math.atan2(dy,dx);c.beginPath();c.moveTo(X(x)+dx-4*Math.cos(angle-.55),Y(y)+dy-4*Math.sin(angle-.55));c.lineTo(X(x)+dx,Y(y)+dy);c.lineTo(X(x)+dx-4*Math.cos(angle+.55),Y(y)+dy-4*Math.sin(angle+.55));c.stroke()}}
if($('layerCurrents').checked&&s.current_u!==undefined&&s.current_v!==undefined)arrows(s.current_u,s.current_v,'#a1dae08c',false);if($('layerWind').checked&&s.wind_u!==undefined&&s.wind_v!==undefined)arrows(s.wind_u,s.wind_v,'#f9dab18c',true);
if($('layerBergs').checked)for(const b of result.tracks){if($('layerEnsemble').checked){c.strokeStyle='#9feaf218';c.lineWidth=.6;for(const p of b.members){c.beginPath();p.forEach(([x,y],i)=>i?c.lineTo(X(x),Y(y)):c.moveTo(X(x),Y(y)));c.stroke()}}c.strokeStyle='#8dd6e5b0';c.lineWidth=1.3;c.setLineDash([4,4]);c.beginPath();b.path.forEach(([x,y],i)=>i?c.lineTo(X(x),Y(y)):c.moveTo(X(x),Y(y)));c.stroke();c.setLineDash([]);const [x,y]=b.path[frame],r=b.radius_km[frame]+result.options.buffer_km;c.strokeStyle='#91d8e384';c.fillStyle='#97dbe810';c.beginPath();c.ellipse(X(x),Y(y),r/result.grid.dx_km*box.w/43,r/result.grid.dy_km*box.h/29,0,0,Math.PI*2);c.fill();c.stroke();c.fillStyle='#d9f6fa';c.beginPath();c.moveTo(X(x),Y(y)-5);c.lineTo(X(x)+5,Y(y)+4);c.lineTo(X(x)-5,Y(y)+4);c.closePath();c.fill();c.font='10px Segoe UI';c.fillText(b.id,X(x)+8,Y(y)-7)}
drawZones(c,X,Y,box);const route=selectedRoute();if($('layerRoutes').checked){for(const r of [...result.routes].sort((a,b)=>(a.mode===route?.mode?1:0)-(b.mode===route?.mode?1:0))){const active=r.mode===route?.mode;c.strokeStyle=active?'#efa767':'#b6d1df66';c.lineWidth=active?2.8:1.1;c.lineJoin='round';c.beginPath();r.path.forEach(([x,y],i)=>i?c.lineTo(X(x),Y(y)):c.moveTo(X(x),Y(y)));c.stroke()}if(route&&route.legs.length){let time=frame*6,i=route.legs.findIndex(l=>l.eta_hours>=time);if(i<0)i=route.legs.length-1;const end=route.legs[i],prev=i?route.legs[i-1]:{cell:s.start,eta_hours:0};let f=Math.min(1,Math.max(0,(time-prev.eta_hours)/(end.eta_hours-prev.eta_hours||1)));let x=prev.cell[0]+f*(end.cell[0]-prev.cell[0]),y=prev.cell[1]+f*(end.cell[1]-prev.cell[1]);c.save();c.translate(X(x),Y(y));c.rotate(Math.atan2((end.cell[1]-prev.cell[1])*box.h/29,(end.cell[0]-prev.cell[0])*box.w/43)+Math.PI/2);c.fillStyle='white';c.strokeStyle='#123e57';c.lineWidth=1.2;c.beginPath();c.moveTo(0,-8);c.lineTo(5,6);c.lineTo(0,3);c.lineTo(-5,6);c.closePath();c.fill();c.stroke();c.restore()}}
for(const [key,label,color] of [['start','Departure','#e6a367'],['goal','Destination','#fff']]){const [x,y]=s[key];c.fillStyle=color;c.strokeStyle='#153d52';c.lineWidth=1.5;c.beginPath();c.arc(X(x),Y(y),4.5,0,Math.PI*2);c.fill();c.stroke();c.font='600 10px Segoe UI';const labelX=x>33?X(x)-67:X(x)+9;c.fillStyle='#143d53';c.fillRect(labelX-3,Y(y)-21,69,15);c.fillStyle='#e8f4fa';c.fillText(label,labelX,Y(y)-10)}
if(!$('cellPopup').hidden){c.strokeStyle='#ffffffba';c.lineWidth=1;c.strokeRect(X(cursor[0])-box.w/86,Y(cursor[1])-box.h/58,box.w/43,box.h/29)}c.restore();$('mapTime').textContent=result.scenario.data_kind==='observational'?(frame?`Persistence +${frame*6} h`:'NOAA analysis'):`Forecast +${frame*6} h`;$('timeLabel').textContent=`+${frame*6} h`;$('mapScale').textContent=fmt(62/(box.w*view.zoom)*(43*result.grid.dx_km),0)+' km';if(!$('cellPopup').hidden)inspectCell();}
function cellFrom(e){const b=mapCanvas.getBoundingClientRect(),w=b.width,h=b.height;let x=((e.clientX-b.left-w/2-view.x)/view.zoom+w/2-plotBox.x)/plotBox.w*43;let y=((e.clientY-b.top-h/2-view.y)/view.zoom+h/2-plotBox.y)/plotBox.h*29;return [Math.round(x),Math.round(y)]}
function inspectCell(){if(!result)return;const [x,y]=cursor,s=result.scenario,why=Object.entries(result.block_reasons).filter(([,g])=>g[y][x]).map(([k])=>k);$('cellPopup').innerHTML=`<b>${esc(prettyCoord(s,cursor))}</b>Cell ${x}, ${y} · ice ${s.missing?.[y]?.[x]?'unavailable':fmt(result.forecasts[frame][y][x]*100,1)+'%'}<br>Wind ${s.wind_u===undefined?'unassessed':fmt(Math.hypot(gridValue(s.wind_u,x,y),gridValue(s.wind_v,x,y)),1)+' m/s'} · current ${s.current_u===undefined?'unassessed':fmt(Math.hypot(gridValue(s.current_u,x,y),gridValue(s.current_v,x,y)),2)+' m/s'}<br>${s.wave_height!==undefined?'Wave '+fmt(gridValue(s.wave_height,x,y),1)+' m · ':''}${s.depth!==undefined?'Depth '+fmt(gridValue(s.depth,x,y),0)+' m':''}${resultInput?.temperature&&!s.missing?.[y]?.[x]&&!s.land[y][x]?'<br>Sea temperature '+fmt(resultInput.temperature[y][x],1)+' °C':''}<br><span class="${why.length?'bad':''}">${why.length?'Excluded: '+esc(why.join(', ')):'Within the current grid constraints'}</span>`;$('cellPopup').hidden=false}
function placeOrInspect(p){if(p[0]<0||p[0]>43||p[1]<0||p[1]>29)return;cursor=p;if(placing==='zone'){if((scenario.exclusion_zones||[]).length>=8)return toast('Maximum eight zones. Undo one to add another.');scenario.exclusion_zones=[...(scenario.exclusion_zones||[]),{x:p[0],y:p[1],radius_km:+$('zoneRadius').value}];placing=null;$('mapInstruction').hidden=true;dirty();calculate();return}if(placing){if(scenario.land[p[1]][p[0]])return toast('Choose a water cell.');scenario[placing]=p;placing=null;$('mapInstruction').hidden=true;updateInputs();dirty();calculate()}else{inspectCell();drawMap()}}
mapCanvas.addEventListener('pointerdown',e=>{if(!result)return;pointer={x:e.clientX,y:e.clientY,ox:view.x,oy:view.y};dragged=false;mapCanvas.setPointerCapture(e.pointerId)});
mapCanvas.addEventListener('pointermove',e=>{if(!pointer)return;const dx=e.clientX-pointer.x,dy=e.clientY-pointer.y;if(Math.hypot(dx,dy)>5){dragged=true;view.x=pointer.ox+dx;view.y=pointer.oy+dy;drawMap()}});
mapCanvas.addEventListener('pointerup',e=>{if(!pointer)return;if(!dragged)placeOrInspect(cellFrom(e));pointer=null});mapCanvas.addEventListener('pointercancel',()=>pointer=null);
mapCanvas.addEventListener('wheel',e=>{if(e.ctrlKey)return;e.preventDefault();view.zoom=Math.max(1,Math.min(5,view.zoom*(e.deltaY>0?.9:1.1)));if(view.zoom===1){view.x=0;view.y=0}drawMap()},{passive:false});
mapCanvas.onkeydown=e=>{const d={ArrowLeft:[-1,0],ArrowRight:[1,0],ArrowUp:[0,-1],ArrowDown:[0,1]}[e.key];if(d){e.preventDefault();cursor=[Math.max(0,Math.min(43,cursor[0]+d[0])),Math.max(0,Math.min(29,cursor[1]+d[1]))];inspectCell();drawMap()}if(e.key==='Enter'){e.preventDefault();placeOrInspect(cursor)}if(e.key==='Escape'){$('cellPopup').hidden=true;placing=null;$('mapInstruction').hidden=true;drawMap()}};
function lineChart(id,series,{xLabel='Forecast lead (hours)',yLabel='Concentration (%)',yMax=null}={}){const size=canvasSize($(id));if(!size)return;const {c,w,h}=size;c.clearRect(0,0,w,h);if(!series.length){c.fillStyle='#78909c';c.font='12px Segoe UI';c.fillText('Calculate and select a route to view its profile.',18,55);return}const left=42,right=15,top=34,bottom=36,pw=w-left-right,ph=h-top-bottom;const all=series.flatMap(s=>s.points),mx=Math.max(1,...all.map(p=>p[0])),my=yMax||Math.max(.01,...all.map(p=>p[1]))*1.15;c.font='10px Segoe UI';for(let i=0;i<=4;i++){const y=top+ph-i*ph/4;c.strokeStyle='#35516a';c.beginPath();c.moveTo(left,y);c.lineTo(w-right,y);c.stroke();c.fillStyle='#a9c7da';c.fillText(fmt(my*i/4,my<1?3:0),2,y+3)}for(let i=0;i<=4;i++){const x=left+pw*i/4;c.fillStyle='#a9c7da';c.fillText(fmt(mx*i/4,0),x-5,h-18)}for(const [si,s] of series.entries()){c.strokeStyle=s.color;c.lineWidth=2.3;c.beginPath();s.points.forEach(([x,y],i)=>i?c.lineTo(left+x/mx*pw,top+ph-y/my*ph):c.moveTo(left+x/mx*pw,top+ph-y/my*ph));c.stroke();c.fillStyle=s.color;c.fillRect(left+si*150,9,15,2);c.fillText(s.name,left+20+si*150,13)}c.fillStyle='#a9c7da';c.font='9px Segoe UI';c.fillText(xLabel,w/2-45,h-2);c.fillText(yLabel,left,top-7)}
function drawProfile(){const r=selectedRoute();lineChart('profileChart',r?.legs.length?[{name:'Route ice exposure',color:'#c28449',points:[[0,result.forecasts[0][result.scenario.start[1]][result.scenario.start[0]]*100],...r.legs.map(l=>[l.distance_km,l.ice_fraction*100])]}]:[],{xLabel:'Passage distance (km)',yLabel:'Ice (%)',yMax:100})}
function drawIce(){if(!result)return;lineChart('iceChart',[{name:'Mean ocean-cell ice',color:'#78d7e8',points:result.stats.ice_mean.map((v,i)=>[i*6,(v||0)*100])}],{yMax:100})}
let evaluation=null;async function evidence(){try{evaluation=evaluation||await api('/api/evaluation');const d=evaluation;lineChart('evalChart',[{name:'Ridge forecast',color:'#78d7e8',points:d.lead_hours.map((x,i)=>[x,d.rmse[i]])},{name:'Persistence',color:'#c28751',points:d.lead_hours.map((x,i)=>[x,d.persistence_rmse[i]])}],{yLabel:'RMSE (fraction)'});$('evalTable').innerHTML='<table><thead><tr><th>Lead</th><th>Ridge RMSE</th><th>Persistence</th></tr></thead><tbody>'+[3,7,11].map(i=>`<tr><td>${d.lead_hours[i]} h</td><td>${fmt(d.rmse[i],4)}</td><td>${fmt(d.persistence_rmse[i],4)}</td></tr>`).join('')+'</tbody></table>';$('modelStats').textContent=`${fmt(d.training_samples,0)} synthetic training transitions. ${d.test_sequences} held-out sequences. No real Antarctic validation.`;drawIce()}catch(e){fail(e.message)}}
function showTab(tab){activeTab=tab;document.querySelectorAll('.tabview').forEach(e=>e.hidden=e.id!==tab);document.querySelectorAll('.navbtn').forEach(b=>{b.classList.toggle('active',b.dataset.tab===tab);b.setAttribute('aria-current',b.dataset.tab===tab?'page':'false')});if(tab==='forecast')evidence();if(tab==='planner'){drawMap();drawProfile()}if(tab==='data')savedList()}
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>showTab(b.dataset.tab));document.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>showTab(b.dataset.open));document.querySelector('.brand').onclick=e=>{e.preventDefault();showTab('planner')};
for(const id of ['speed','iceLimit','buffer','wind','maxWave','draft'])$(id).oninput=()=>{labels();dirty()};for(const id of ['horizon','forecastMethod'])$(id).onchange=dirty;
$('run').onclick=calculate;$('dirtyRun').onclick=calculate;
async function loadScenario(){if(loading)return toast('Wait for the current calculation.');try{if($('scenario').value==='observed')return loadObserved();scenario=await api('/api/scenario?kind='+$('scenario').value);view={zoom:1,x:0,y:0};$('forecastMethod').value='ridge';updateInputs();await calculate()}catch(e){fail(e.message)}}$('scenario').onchange=loadScenario;$('reset').onclick=()=>{applyOptions({horizon:72,speed:12,ice_limit:.65,buffer_km:12,wind_scale:1,max_wave:4,vessel_draft:8,forecast_method:'ridge'});loadScenario()};
$('time').oninput=()=>{stop();frame=+$('time').value;drawMap()};$('play').onclick=()=>{if(!result)return;if(playTimer)return stop();$('play').innerHTML=icon('pause');$('play').setAttribute('aria-label','Pause forecast');playTimer=setInterval(()=>{frame=(frame+1)%result.forecasts.length;$('time').value=frame;drawMap()},+$('playSpeed').value)};
for(const [id,key] of [['setStart','start'],['setGoal','goal']])$(id).onclick=()=>{placing=key;$('mapInstruction').hidden=false;toast('Click a water cell, or use arrow keys and Enter on the chart.');mapCanvas.focus({preventScroll:true})};$('cancelPoint').onclick=()=>{placing=null;$('mapInstruction').hidden=true};
$('applyCoords').onclick=()=>{const p=[+$('startX').value,+$('startY').value],q=[+$('goalX').value,+$('goalY').value];if([...p,...q].some(v=>!Number.isInteger(v))||p[0]<0||p[0]>43||q[0]<0||q[0]>43||p[1]<0||p[1]>29||q[1]<0||q[1]>29)return fail('Enter columns 0–43 and rows 0–29.');scenario.start=p;scenario.goal=q;updateInputs();dirty();calculate()};
$('zoomIn').onclick=()=>{view.zoom=Math.min(5,view.zoom*1.3);drawMap()};$('zoomOut').onclick=()=>{view.zoom=Math.max(1,view.zoom/1.3);if(view.zoom===1)view.x=view.y=0;drawMap()};$('fitMap').onclick=()=>{view={zoom:1,x:0,y:0};drawMap()};$('fullMap').onclick=()=>{$('planner').classList.toggle('expanded-map');requestAnimationFrame(drawMap)};document.querySelectorAll('.layerbar input').forEach(e=>e.onchange=drawMap);
function bergEditor(){$('bergEditor').innerHTML=editBergs.map((b,i)=>`<div class="berg-edit" data-berg="${i}">${[['id','Name','text'],['x','Column','number'],['y','Row','number'],['sail','Sail (m)','number'],['draft','Draft (m)','number']].map(([k,label,type])=>`<label>${label}<input data-field="${k}" type="${type}" value="${esc(b[k])}" ${type==='number'?'step="any"':''} required></label>`).join('')}<button type="button" class="quiet" data-remove="${i}" aria-label="Remove ${esc(b.id)}">×</button></div>`).join('')}
function readBergs(){return [...$('bergEditor').querySelectorAll('[data-berg]')].map(e=>Object.fromEntries([...e.querySelectorAll('[data-field]')].map(a=>[a.dataset.field,a.dataset.field==='id'?a.value:+a.value])))}
$('manageBergs').onclick=()=>{editBergs=clone(scenario.icebergs);bergEditor();$('bergDialog').showModal()};$('closeBergs').onclick=()=>$('bergDialog').close();$('addBerg').onclick=()=>{editBergs=readBergs();if(editBergs.length>=20)return toast('Maximum 20 iceberg records.');let id='Berg '+(editBergs.length+1);while(editBergs.some(b=>b.id===id))id+='+';editBergs.push({id,x:cursor[0],y:cursor[1],sail:10,draft:90});bergEditor()};$('bergEditor').onclick=e=>{if(e.target.dataset.remove!==undefined){editBergs=readBergs();editBergs.splice(+e.target.dataset.remove,1);bergEditor()}};$('bergForm').onsubmit=e=>{e.preventDefault();scenario.icebergs=readBergs();$('bergDialog').close();dirty();calculate()};
function saved(){try{return JSON.parse(localStorage.getItem('polarroute-voyages-v2')||'[]')}catch{return []}}
function saveMission(){if(!scenario)return;try{let list=saved();list.unshift({name:scenario.name,date:new Date().toISOString(),scenario:clone(scenario),options:options()});localStorage.setItem('polarroute-voyages-v2',JSON.stringify(list.slice(0,6)));savedList();toast('Voyage saved in this browser.')}catch{toast('Browser storage is unavailable or full. Export JSON instead.')}}$('saveMission').onclick=saveMission;$('saveMission2').onclick=saveMission;
function savedList(){$('savedMissions').innerHTML=saved().map((m,i)=>`<div class="saved-row"><div><b>${esc(m.name)}</b><small>${esc(new Date(m.date).toLocaleString())}</small></div><button class="quiet" data-load="${i}">Load</button></div>`).join('')||'<p class="hint">No saved voyages yet. Save a scenario to compare another plan later.</p>'}
$('savedMissions').onclick=e=>{if(e.target.dataset.load!==undefined&&!loading){const m=saved()[+e.target.dataset.load];scenario=clone(m.scenario);applyOptions(m.options);updateInputs();showTab('planner');calculate()}};
$('sampleJSON').onclick=()=>scenario&&download('polarroute-scenario.json',scenario);
$('sampleCSV').onclick=()=>{if(!scenario)return;if(scenario.data_kind==='observational')return toast('Use Scenario JSON to preserve observation masks, missing forcing and attribution.');const s=scenario,cols=['longitude','latitude','current','previous','temperature','land','wind_u','wind_v','current_u','current_v','wave_height','depth','observed_at'];let lines=[cols.join(',')];for(let y=0;y<30;y++)for(let x=0;x<44;x++){const [lon,lat]=coord(s,[x,y]);lines.push([lon,lat,...cols.slice(2,-1).map(k=>Number(gridValue(s[k]??(k==='depth'?10000:0),x,y))),s.observed_at].join(','))}download('polarroute-grid.csv',lines.join('\n'),'text/csv')};
$('importFile').onchange=async e=>{if(loading)return toast('Wait for the current calculation before importing.');const file=e.target.files[0];if(!file)return;loading=true;stop();try{if(file.size>2000000)throw Error('Maximum import size is 2 MB.');const text=await file.text();const s=file.name.toLowerCase().endsWith('.csv')?await api('/api/import-csv',{csv:text,name:file.name.replace(/\.csv$/i,'')}):JSON.parse(text);const input=s.input_scenario||(s.scenario&&s.options?s.scenario:s);const opts=s.options||options();const checked=await api('/api/run',{scenario:input,options:opts});scenario=input;result=checked;resultInput=clone(input);stop();applyOptions(checked.options);frame=0;$('time').value=0;$('time').max=result.forecasts.length-1;view={zoom:1,x:0,y:0};$('dirty').hidden=true;fail('');refresh();showTab('planner');toast('Imported, validated and calculated.')}catch(e){fail('Import rejected: '+e.message)}finally{loading=false;$('importFile').value=''}};
$('saveMeta').onclick=()=>{scenario.name=$('sourceName').value;scenario.source=$('sourceText').value;scenario.observed_at=$('observedAt').value;dirty();calculate()};
$('exportReport').onclick=()=>result&&download('polarroute-result.json',{...result,input_scenario:resultInput});
$('exportGeo').onclick=()=>{if(!result)return;download('polarroute-routes.geojson',{type:'FeatureCollection',features:result.routes.map(r=>({type:'Feature',properties:{name:names[r.mode],distance_km:r.distance_km,eta_hours:r.eta_hours,fuel_proxy:r.fuel_index,source:result.scenario.source,run:result.stats.run_id,warning:'Research prototype; not for navigation'},geometry:{type:r.path.length===1?'Point':'LineString',coordinates:r.path.length===1?coord(result.scenario,r.path[0]):r.path.map(p=>coord(result.scenario,p))}}))},'application/geo+json')};
$('exportLegs').onclick=()=>{const r=selectedRoute();if(!r)return toast('Calculate an accepted route first.');download('polarroute-waypoints.csv','longitude,latitude,cumulative_km,eta_hours,ice_fraction,wave_m\n'+[coord(result.scenario,result.scenario.start).join(',')+',0,0,,',...r.legs.map(l=>[...l.lonlat,l.distance_km,l.eta_hours,l.ice_fraction,l.wave_m].join(','))].join('\n'),'text/csv')};
$('exportBrief').onclick=()=>{if(!result)return;const r=selectedRoute();const lines=['# PolarRoute voyage brief','',`Scenario: ${result.scenario.name}`,`Source: ${result.scenario.source}`,`Observation: ${result.scenario.observed_at}`,`Run: ${result.stats.run_id}`,'',r?`Selected: ${names[r.mode]} | ${r.distance_km} km | ${r.eta_hours} h | fuel proxy ${r.fuel_index} | mean ice ${fmt(r.mean_ice*100,1)}%`:'No accepted route.','',`Limits: ice ${result.options.ice_limit*100}%, waves ${result.options.max_wave} m, draft ${result.options.vessel_draft} m + 3 m margin, iceberg clearance ${result.options.buffer_km} km.`,`Forecast horizon: ${result.options.horizon} h; method: ${result.options.forecast_method}.`,'','## Decision notes',...result.warnings.map(w=>'- '+w),'','## Scientific limitations',...result.limitations.map(w=>'- '+w)];download('polarroute-voyage-brief.md',lines.join('\n'),'text/markdown')};
new ResizeObserver(()=>{if(activeTab==='planner'){drawMap();drawProfile()}else if(activeTab==='forecast'){evidence();drawIce()}}).observe($('mapStage'));
window.addEventListener('resize',()=>{if(activeTab==='forecast')evidence();drawProfile()});
let fieldView='ice', pinnedPlan=null;
const papers=[
 {tag:'antarctic',year:'2023',journal:'Geophysical Research Letters',name:'SIPNet',title:'Subseasonal Prediction of Regional Antarctic Sea Ice by a Deep Learning Model',url:'https://doi.org/10.1029/2023GL104347',scope:'Antarctic · weekly forecasts · 1–8 weeks',idea:'Uses historical sea-ice concentration to forecast regional Antarctic ice at subseasonal lead times.',use:'A relevant starting point for Antarctic training data and regional evaluation.',gap:'Weekly predictions do not directly validate our six-hour prototype. SIPNet is not deployed here.'},
 {tag:'antarctic',year:'2025',journal:'The Cryosphere',name:'ANTSIC-UNet',title:'Extended seasonal prediction of Antarctic sea ice concentration using ANTSIC-UNet',url:'https://doi.org/10.5194/tc-19-6381-2025',scope:'Antarctic · seasonal · up to 6 months',idea:'Combines multiple climate variables in a U-Net and evaluates concentration and ice-edge errors.',use:'Guides multivariable input selection and comparison with persistence and linear-trend baselines.',gap:'Its seasonal horizon differs from voyage planning. Published skill is not evidence for this app.'},
 {tag:'physics',year:'2017',journal:'Journal of Physical Oceanography',name:'Iceberg drift physics',title:'An Analytical Model of Iceberg Drift',url:'https://doi.org/10.1175/JPO-D-16-0262.1',scope:'Iceberg size · wind · ocean currents',idea:'Explains why iceberg size changes the balance between wind and current-driven motion.',use:'Motivates geometry-aware drift and cautions against applying a fixed wind rule to large Antarctic tabular icebergs.',gap:'Our reduced sail/draft baseline omits important physics and does not reproduce the paper’s full model.'},
 {tag:'arctic',year:'2021',journal:'Nature Communications',name:'IceNet',title:'Seasonal Arctic sea ice forecasting with probabilistic deep learning',url:'https://doi.org/10.1038/s41467-021-25257-4',scope:'Arctic · monthly averages · up to 6 months',idea:'Uses probabilistic deep learning for seasonal sea-ice forecasts and examines calibration.',use:'A reference for uncertainty evaluation and separating predicted probabilities from raw ensemble spread.',gap:'Arctic evidence cannot be treated as Antarctic validation. This app does not use IceNet weights.'}
];
function renderPapers(filter='all'){
 $('paperCards').innerHTML=papers.filter(p=>filter==='all'||p.tag===filter).map(p=>`<article class="paper"><div class="paper-top"><span>${esc(p.journal)}</span><strong>${p.year}</strong></div><h2>${esc(p.name)}</h2><p class="paper-scope">${esc(p.scope)}</p><p>${esc(p.idea)}</p><details><summary>How it relates to PolarRoute</summary><p>${esc(p.use)}</p><p class="paper-gap">${esc(p.gap)}</p></details><a href="${p.url}" target="_blank" rel="noreferrer">Read the paper ↗</a><small>${esc(p.title)}</small></article>`).join('');
}
document.querySelectorAll('[data-paper-filter]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-paper-filter]').forEach(x=>{x.classList.toggle('active',x===b);x.setAttribute('aria-pressed',String(x===b))});renderPapers(b.dataset.paperFilter)});
function readingNotes(){return '# PolarRoute research reading notes\n\nReviewed 3 October 2026. Published models are references, not implementations in this prototype.\n\n'+papers.map(p=>`## ${p.name} (${p.year})\n\n${p.title}\n${p.journal}\n${p.url}\n\nScope: ${p.scope}\n\n${p.idea}\n\nUse: ${p.use}\n\nLimit: ${p.gap}\n`).join('\n')}
$('exportReading').onclick=()=>download('PolarRoute-research-notes.md',readingNotes(),'text/markdown');renderPapers();
function fieldColor(x,y,land){
 if(land)return [66,87,118];if(result.scenario.missing?.[y]?.[x])return [43,54,75];if(fieldView==='sst'){const temp=resultInput?.temperature?.[y]?.[x];if(temp===undefined)return [43,54,75];const v=Math.max(0,Math.min(1,(temp+2)/7));return [23+213*v,135+32*v,169-73*v]}
 let v=result.forecasts[frame][y][x];
 if(fieldView==='waves'){const wave=result.scenario.wave_height;if(wave===undefined)return [64,76,88];v=Math.min(1,gridValue(wave,x,y)/6);return [26+218*v,98+63*v,133-41*v]}
 if(fieldView==='depth'){const depth=result.scenario.depth;if(depth===undefined)return [64,76,88];v=Math.min(1,gridValue(depth,x,y)/2000);return [130-117*v,207-160*v,215-130*v]}
 const stops=[[12,50,77],[30,112,149],[104,179,198],[227,245,243]];const q=Math.min(2.999,v*3),i=Math.floor(q),f=q-i;return stops[i].map((n,k)=>n+(stops[i+1][k]-n)*f);
}
function drawContours(c,X,Y,box){
 if(fieldView!=='ice')return;
 // Grid boundaries show concentration bands without pretending to be a satellite image.
 c.lineWidth=.6;c.strokeStyle='#d3f1f04a';
 for(const threshold of [.15,.4,.7]){c.beginPath();for(let y=0;y<29;y++)for(let x=0;x<43;x++){if(result.scenario.land[y][x]||result.scenario.missing?.[y]?.[x])continue;const here=result.forecasts[frame][y][x]>=threshold;if(here!==(result.forecasts[frame][y][x+1]>=threshold)){c.moveTo(X(x+.5),Y(y-.5));c.lineTo(X(x+.5),Y(y+.5))}if(here!==(result.forecasts[frame][y+1][x]>=threshold)){c.moveTo(X(x-.5),Y(y+.5));c.lineTo(X(x+.5),Y(y+.5))}}c.stroke()}
}
function drawZones(c,X,Y,box){
 for(const [i,z] of (result.scenario.exclusion_zones||[]).entries()){c.strokeStyle='#ffa18d';c.fillStyle='#ef765529';c.lineWidth=1.6;c.setLineDash([5,4]);c.beginPath();c.ellipse(X(z.x),Y(z.y),z.radius_km/result.grid.dx_km*box.w/43,z.radius_km/result.grid.dy_km*box.h/29,0,0,Math.PI*2);c.fill();c.stroke();c.setLineDash([]);c.fillStyle='#ffe1da';c.font='11px Segoe UI';c.fillText('Exclusion '+(i+1),X(z.x)+7,Y(z.y)-7)}
}
document.querySelectorAll('[data-field-view]').forEach(b=>b.onclick=()=>{fieldView=b.dataset.fieldView;document.querySelectorAll('[data-field-view]').forEach(x=>{x.classList.toggle('active',x===b);x.setAttribute('aria-pressed',String(x===b))});const labels={ice:['Sea ice','0%','100%','#0c324d,#e3f5f3'],waves:['Wave height · static','0 m','6+ m','#1a6285,#f4a15c'],depth:['Depth · static','0 m','2,000+ m','#82cfd7,#0d2f55'],sst:['Sea temperature','−2°C','5+°C','#1787a9,#eca760']}[fieldView];['fieldName','fieldMin','fieldMax'].forEach((id,i)=>$(id).textContent=labels[i]);$('fieldGradient').style.background='linear-gradient(90deg,'+labels[3]+')';if(result&&!['ice','sst'].includes(fieldView)&&result.scenario[fieldView==='waves'?'wave_height':'depth']===undefined)toast('This field was not supplied; grey means unassessed.');drawMap()});
function stepFrame(delta){if(!result)return;stop();frame=Math.max(0,Math.min(result.forecasts.length-1,frame+delta));$('time').value=frame;drawMap()}
$('prevFrame').onclick=()=>stepFrame(-1);$('nextFrame').onclick=()=>stepFrame(1);$('playSpeed').onchange=()=>{if(playTimer){stop();$('play').click()}};
$('addZone').onclick=()=>{if(!scenario||loading)return toast('Wait for a completed calculation.');placing='zone';$('mapInstruction').firstChild.textContent='Click the centre of an exclusion area. ';$('mapInstruction').hidden=false;mapCanvas.focus({preventScroll:true});toast('Choose the centre on the map. Routes will be recalculated.')};
for(const id of ['setStart','setGoal'])$(id).addEventListener('click',()=>{$('mapInstruction').firstChild.textContent='Click a water cell to place the endpoint. '});
$('undoZone').onclick=()=>{if(loading)return;if(!scenario?.exclusion_zones?.length)return toast('No exclusion zones to undo.');scenario.exclusion_zones.pop();dirty();calculate()};
$('jumpSettings').onclick=()=>{document.querySelector('.controls').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'start'});$('horizon').focus({preventScroll:true})};
$('help').onclick=()=>$('guideDialog').showModal();$('closeGuide').onclick=()=>$('guideDialog').close();$('startGuide').onclick=()=>{$('guideDialog').close();mapCanvas.focus({preventScroll:true})};
$('snapshotMap').onclick=()=>{if(!result)return;const a=document.createElement('a');const c=document.createElement('canvas');c.width=mapCanvas.width;c.height=mapCanvas.height+80;const context=c.getContext('2d');context.fillStyle='#10364e';context.fillRect(0,0,c.width,c.height);context.drawImage(mapCanvas,0,0);context.fillStyle='#e2eef5';context.font='16px Segoe UI';context.fillText(`PolarRoute | ${result.scenario.name} | +${frame*6} h | ${fieldView}`,18,mapCanvas.height+28);context.font='13px Segoe UI';context.fillText('Research prototype. '+(result.scenario.data_kind==='synthetic'?'Synthetic fields and fictional coastline.':'Imported data; verify source quality.')+' Not for navigation.',18,mapCanvas.height+55);a.href=c.toDataURL('image/png');a.download='polarroute-chart.png';a.click()};
function updateMission(){
 if(!result)return;const r=selectedRoute();$('missionState').textContent=r?`${result.routes.length} passage options ready`:'No passage meets these constraints';$('missionDetail').textContent=r?`${names[r.mode]} selected · ${result.options.horizon}-hour forecast · ${result.tracks.length} iceberg records`:'Review the exclusion layers, endpoints and forecast horizon.';$('zoneCount').textContent=(result.scenario.exclusion_zones||[]).length+' zones';
 $('routeTable').innerHTML=result.routes.length?result.routes.map(p=>`<tr class="${p.mode===r.mode?'chosen':''}"><td><button data-select-route="${p.mode}" aria-pressed="${p.mode===r.mode}">${names[p.mode]}</button></td><td>${fmt(p.distance_km,1)} km</td><td>${fmt(p.eta_hours,1)} h</td><td>${fmt(p.mean_ice*100,1)}%</td><td>${fmt(p.fuel_index,0)}</td></tr>`).join(''):'<tr><td colspan="5">No accepted route. Inspect Decision notes for the blocking constraints.</td></tr>';
 const c=$('comparison');c.hidden=!pinnedPlan;if(!pinnedPlan)return;
 const sameRegion=JSON.stringify(result.scenario.bounds)===JSON.stringify(pinnedPlan.bounds)&&JSON.stringify(result.scenario.start)===JSON.stringify(pinnedPlan.start)&&JSON.stringify(result.scenario.goal)===JSON.stringify(pinnedPlan.goal);
 const diff=(a,b,suffix)=>{const d=a-b;return (d>=0?'+':'')+fmt(d,1)+suffix};
 c.innerHTML=`<div><strong>Pinned: ${esc(pinnedPlan.name)} / ${names[pinnedPlan.route.mode]}</strong><small>Run ${pinnedPlan.run} · ${pinnedPlan.route.distance_km} km · ${pinnedPlan.route.eta_hours} h</small></div>${r&&sameRegion?`<div><b>${diff(r.distance_km,pinnedPlan.route.distance_km,' km')}</b><small>Distance change</small></div><div><b>${diff(r.eta_hours,pinnedPlan.route.eta_hours,' h')}</b><small>Transit change</small></div><div><b>${diff(r.mean_ice*100,pinnedPlan.route.mean_ice*100,' pp')}</b><small>Mean ice change</small></div>`:`<p>${r?'Different endpoints or region: direct differences are not comparable.':'Current plan has no accepted route.'}</p>`}<button id="clearPin" class="textbtn">Clear pin</button>`;$('clearPin').onclick=()=>{pinnedPlan=null;updateMission()};
}
$('pinPlan').onclick=()=>{const r=selectedRoute();if(!r)return toast('Calculate and select an accepted route first.');if(!$('dirty').hidden)return toast('Calculate changed inputs before pinning.');pinnedPlan={name:result.scenario.name,run:result.stats.run_id,route:clone(r),bounds:clone(result.scenario.bounds),start:clone(result.scenario.start),goal:clone(result.scenario.goal)};updateMission();toast('Plan pinned. Change inputs and calculate to compare.')};
$('routeTable').onclick=e=>{const b=e.target.closest('[data-select-route]');if(b){selected=b.dataset.selectRoute;routes();drawMap();updateMission()}};


async function loadObserved(){
 if(loading)return toast('Wait for the current calculation.');
 loading=true;stop();fail('');$('loadObservations').disabled=true;$('dataLoadStatus').textContent='Loading dated NOAA analysis and ERA5 wind…';
 try{const input=await api('/api/observations?date='+encodeURIComponent($('analysisDate').value));scenario=input;$('scenario').value='observed';applyOptions({forecast_method:'persistence'});view={zoom:1,x:0,y:0};updateInputs();loading=false;await calculate();$('dataLoadStatus').textContent='Loaded '+input.observed_at.slice(0,10)+' · '+input.sources.length+' source records';}
 catch(e){fail(e.message);$('dataLoadStatus').textContent='Data load failed. Previous results remain visible.';}
 finally{loading=false;$('loadObservations').disabled=false;}
}
$('loadObservations').onclick=loadObserved;
function updateSources(){
 if(!result)return;const s=result.scenario;const actual=s.data_kind==='observational';
 $('mapAttribution').textContent=actual?'Made with Natural Earth · NOAA OISST v2.1 · '+s.observed_at.slice(0,10):'Synthetic or imported chart · source details in Data workspace';
 $('observationSummary').textContent=actual?'NOAA ice + sea temperature; ERA5 wind where available':'Synthetic/imported scenario active';
 $('connectedSources').innerHTML=(s.sources||[]).map(a=>`<div class="source-connected"><strong>${esc(a.name)}</strong><span>${esc(a.kind)}</span><small>${esc(a.date)}</small></div>`).join('')||'<p class="hint">No provider records for this scenario.</p>';
 $('forecastMethod').querySelector('option[value="ridge"]').disabled=actual;
 for(const [id,k] of [['layerCurrents','current_u'],['layerWind','wind_u']]){$(id).disabled=s[k]===undefined;if(s[k]===undefined)$(id).checked=false;}
 if(actual){$('layerWind').checked=s.wind_u!==undefined;$('layerCurrents').checked=false;drawMap();}
}
function drawGeography(c,X,Y,box){
 const s=result.scenario;if(!s.coastline)return;
 const point=p=>[43*(p[0]-s.bounds[0])/(s.bounds[2]-s.bounds[0]),29*(s.bounds[3]-p[1])/(s.bounds[3]-s.bounds[1])];
 c.save();c.beginPath();c.rect(box.x-box.w/86,box.y-box.h/58,box.w*44/43,box.h*30/29);c.clip();
 c.fillStyle='#334e6c';c.strokeStyle='#b4e2ee';c.lineWidth=1.2;
 for(const rings of s.coastline){c.beginPath();for(const ring of rings){ring.forEach((p,i)=>{const [x,y]=point(p);i?c.lineTo(X(x),Y(y)):c.moveTo(X(x),Y(y))});c.closePath()}c.fill('evenodd');c.stroke()}
 c.strokeStyle='#d4a47555';c.lineWidth=.7;
 for(let y=0;y<30;y++)for(let x=0;x<44;x++)if(s.missing?.[y]?.[x]){c.beginPath();c.moveTo(X(x)-box.w/86,Y(y)+box.h/58);c.lineTo(X(x)+box.w/86,Y(y)-box.h/58);c.stroke()}
 c.restore();
}

async function init(){try{labels();savedList();await loadObserved()}catch(e){fail('Cannot load the local workspace: '+e.message)}}init();
